Migrate state mutations (block/uncle rewards, dao) to params/mutations
etclabscore/core-geth pull request #335
Opened 2021-03-12 17:26 UTC by iquidus

Introduces a new "mutations" module (found in params/mutations/*), intended for state mutations that take place outside of standard transactions, e.g block/uncle rewards, dao.

This logic has traditionally been located within the consensus/ethash and consensus/misc modules. Given these state mutations are likely to vary between chains (And are not technically part of ethash) it makes more sense to keep them in params.

No changes have been made to chain configs. 

reference #20

2021-03-12 19:29 UTC, meowsbits reviewed
I'm not sure the `--mainnet` flag commit belongs in this branch, or? 

https://github.com/etclabscore/core-geth/pull/335/commits/4ed1399fd4f577be676fb06d2ddffe2e0032cddf

2021-03-12 23:48 UTC, iquidus commented
> I'm not sure the `--mainnet` flag commit belongs in this branch, or?
> 
> [4ed1399](https://github.com/etclabscore/core-geth/commit/4ed1399fd4f577be676fb06d2ddffe2e0032cddf)

I have no idea what you are talking about ;)

Was a mistake, didn't notice my master wasn't clean before branching. Removed.

2021-03-17 12:06 UTC, meowsbits approved these changes
Looks fine to me. Per a team chat yesterday, there may be some unit tests for rewards in the works. Up to you @iquidus if you want to include those in the PR or a later one.

2021-03-24 07:07 UTC, ziogaschr commented
LGTM too! Nice decoupling

2021-03-25 12:21 UTC, meowsbits commented
@iquidus Do you intend this to be ready for re-review/merge at this point?

2021-03-25 12:24 UTC, meowsbits requested changes
Eventually I'd suggest the commit message https://github.com/etclabscore/core-geth/pull/335/commits/41fa2e43a950a0df6b5a34ada81db8044d3e65cf include more information.

2021-04-02 14:44 UTC, iquidus commented on params/mutations/rewards_test.go
> +*/
This test (from the old code), still needs resolving. It runs (after refactor), but fails massively, further study required.

2021-04-02 14:45 UTC, iquidus commented on params/mutations/rewards_test.go
> +}
duplicate tests to a degree, however I figure more never hurts (ported over from core-pool).

2021-04-10 10:45 UTC, iquidus commented on params/mutations/rewards_test.go
> +*/
resolved.

2021-04-10 11:07 UTC, iquidus commented
typo in commit message c3b1080

2021-04-12 12:57 UTC, meowsbits commented
This is looking good! 

What do you think about creating an additional [regression test](https://github.com/etclabscore/core-geth/tree/master/tests/regression/simulated) to have a full end-to-end test focusing on block rewards? 

Indeed, there are tests that touch and handle it, but I don't believe they cover some important configs (which is what I'm always worried about...:wink:) 

Like test a "condensed" ETC config with ECIP1017 Era Rounds of `100` or something with a chain of length 100, with some random uncles in there for good measure?

2021-04-12 13:00 UTC, meowsbits commented
Ah, maybe I am on tracks I have already walked. https://github.com/etclabscore/core-geth/blob/master/tests/regression/simulated/classic-condense-state/classic.conf.json#L32

2021-04-12 13:04 UTC, meowsbits approved these changes

2021-04-12 13:09 UTC, meowsbits commented
Just waiting for some moar tests to finish locally.

2021-04-12 13:39 UTC, meowsbits commented
@iquidus Any idea why I'm getting this on this branch locally?

```
make all
make[1]: Entering directory '/home/ia/go/src/github.com/ethereum/go-ethereum'
env GO111MODULE=on go run build/ci.go install
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/abidump ./cmd/abidump
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/abigen ./cmd/abigen
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/ancient-store-mem ./cmd/ancient-store-mem
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/bootnode ./cmd/bootnode
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/checkpoint-admin ./cmd/checkpoint-admin
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/clef ./cmd/clef
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/devp2p ./cmd/devp2p
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/echaindb ./cmd/echaindb
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/echainspec ./cmd/echainspec
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/ethkey ./cmd/ethkey
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/evm ./cmd/evm
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/faucet ./cmd/faucet
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/geth ./cmd/geth
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/p2psim ./cmd/p2psim
>>> /home/ia/go1.16.2.linux-amd64/bin/go build -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -v -o /home/ia/go/src/github.com/ethereum/go-ethereum/build/bin/rlpdump ./cmd/rlpdump
make[1]: Leaving directory '/home/ia/go/src/github.com/ethereum/go-ethereum'
make test
make[1]: Entering directory '/home/ia/go/src/github.com/ethereum/go-ethereum'
env GO111MODULE=on go run build/ci.go test
>>> /home/ia/go1.16.2.linux-amd64/bin/go test -ldflags -X main.gitCommit=410cb0df3b3da9b1c7ae22a1100822bbe04e2e96 -X main.gitDate=20210410 -p 1 ./...
?       github.com/ethereum/go-ethereum [no test files]
ok      github.com/ethereum/go-ethereum/accounts        (cached)
ok      github.com/ethereum/go-ethereum/accounts/abi    (cached)
--- FAIL: TestGolangBindings (0.14s)
    bind_test.go:1758: failed to run binding test: exit status 1
        callbackparam.go:10:2: module github.com/ethereum/go-ethereum provides package github.com/ethereum/go-ethereum and is replaced but not required; to add it:
                go get github.com/ethereum/go-ethereum
        callbackparam.go:11:2: module github.com/ethereum/go-ethereum provides package github.com/ethereum/go-ethereum/accounts/abi and is replaced but not required; to add it:
                go get github.com/ethereum/go-ethereum
        callbackparam.go:12:2: module github.com/ethereum/go-ethereum provides package github.com/ethereum/go-ethereum/accounts/abi/bind and is replaced but not required; to add it:
                go get github.com/ethereum/go-ethereum
        callbackparam.go:13:2: module github.com/ethereum/go-ethereum provides package github.com/ethereum/go-ethereum/common and is replaced but not required; to add it:
                go get github.com/ethereum/go-ethereum
        callbackparam.go:14:2: module github.com/ethereum/go-ethereum provides package github.com/ethereum/go-ethereum/core/types and is replaced but not required; to add it:
                go get github.com/ethereum/go-ethereum
        callbackparam.go:15:2: module github.com/ethereum/go-ethereum provides package github.com/ethereum/go-ethereum/event and is replaced but not required; to add it:
                go get github.com/ethereum/go-ethereum
FAIL
FAIL    github.com/ethereum/go-ethereum/accounts/abi/bind       0.170s
ok      github.com/ethereum/go-ethereum/accounts/abi/bind/backends      (cached)
?       github.com/ethereum/go-ethereum/accounts/external       [no test files]
^Csignal: interrupt
Makefile:40: recipe for target 'test' failed
make[1]: *** [test] Error 1
.ia/Makefile:8: recipe for target 'check_simple' failed
make: *** [check_simple] Interrupt
```

2021-04-12 14:03 UTC, meowsbits commented
This problem goes away once merged with `master`.

2021-04-12 14:05 UTC, meowsbits approved these changes

2021-04-12 14:08 UTC, iquidus commented
> --- FAIL: TestGolangBindings (0.14s)

iirc I encountered this with go 1.16, i reverted back to 1.15 (with intentions to look at it later), however i believe it was fixed in master.

2021-04-13 13:27 UTC, meowsbits commented
@ziogaschr PTAL and review just for a second opinion, since this is consensus-sensitive code.

2021-04-26 12:16 UTC, iquidus commented
classic mainnet sync: complete.
ethereum mainnet sync: in progress.

2021-04-26 13:36 UTC, ziogaschr approved these changes
LGTM. I am waiting for sync to finish on classic on my side too.

2021-04-26 22:16 UTC, iquidus commented
ethereum mainnet sync: sync'd up to block 12 244 000 (berlin activation)

2021-05-21 17:13 UTC, meowsbits requested changes
Just giving a red review to remind that this PR has `master` as a base branch; I think it should want `rc1` as the base now.

2021-05-22 10:06 UTC, iquidus commented
note: there's a failing openrpc test, inherited from the rc-1 branch.

2021-05-22 14:25 UTC, meowsbits commented
@iquidus I'm not sure I see the failing test you're referencing? 
The `push` build at the `rc1` branch is passing https://travis-ci.org/github/etclabscore/core-geth/builds/770798087, and the failing `pr` build here looks to be the fault of timing out on the H-Z step https://travis-ci.org/github/etclabscore/core-geth/jobs/771926408

Can you give instructions for reproduction, or source where you're seeing the test failure?

2021-05-25 13:01 UTC, iquidus commented
the openrpc failure can be ignored. This was purely a local issue. 

Docker (potentially hung from earlier tests), still had port 8545 occupied (tcp6 - LISTENING). Killing docker, freeing the port, has resolved the failure.

2021-05-25 13:51 UTC, iquidus commented
merged into #376

2021-05-31 15:14 UTC, closed without merging