Set activation blocks for Magneto on classic|mordor|kotti chains
etclabscore/core-geth pull request #368
Opened 2021-04-29 09:40 UTC by ziogaschr

The ECIP https://github.com/ethereumclassic/ECIPs/pull/411 is still in draft mode. So I opened this PR with `A3-inprogress` label assigned.

It's complimentary to #365.

2021-05-10 10:05 UTC, q9f commented
putting this on ice. should go through ecip first. I'll confirm the numbers today 👍🏼

2021-05-10 10:34 UTC, q9f commented
I'm coming up with these numbers, given that we need to go through consensus first.

- mordor in 6 weeks
- kotti in 8 weeks
- mainnet in 12 weeks

block_now | time_to_fork | block_time | fork_block | fork_date
--- | --- | --- | --- | ---
3_835_521 | 3807180 | 15 | 4_089_333 | 2021-06-23
4_205_235 | 5016780 | 15 | 4_539_687 | 2021-07-07
12_713_732 | 7435920 | 13 | 13_285_725 | 2021-08-04

2021-05-10 12:17 UTC, meowsbits requested changes
Requesting changes as an indicator this needs to pass ECIP legislation first.

2021-05-10 15:15 UTC, q9f commented
see https://github.com/ethereumclassic/ECIPs/issues/424

2021-05-18 14:58 UTC, meowsbits commented on params/config_classic.go
> +		EIP2315FBlock: big.NewInt(11),
2315 will be removed.

2021-05-25 11:52 UTC, ziogaschr commented
Closing PR as #385 replaces this one.

2021-05-25 11:52 UTC, closed without merging