params: ECIP1088 feature activation numbers
etclabscore/core-geth pull request #48
Opened 2020-02-27 17:11 UTC by meowsbits

> https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1088.md

The block numbers for Mordor and Kotti are still, AFAIU, somewhat unstable.

These initially proposed numbers (at https://github.com/etclabscore/core-geth/commit/cf93f231a9f331ec94e854891dff1a8ec05c173b) are taken from investigation via #38 to find the latest-viable numbers the chains can reach before the now-nullified Aztlan features would fork the networks.

2020-02-28 06:05 UTC, q9f requested changes
please fix the testnet block numbers according to the ecip 1088

https://ecips.ethereumclassic.org/ECIPs/ecip-1088

2020-02-28 06:05 UTC, q9f commented on params/config_mordor.go
> +		EIP152FBlock:  big.NewInt(839_246),
`999_983` on mordor

2020-02-28 06:05 UTC, q9f commented on params/config_kotti.go
> +		EIP152FBlock:  big.NewInt(2_125_017),
`2_200_013` on kotti

2020-02-28 06:05 UTC, q9f commented
ref https://github.com/ChainSafe/besu/pull/26/

2020-03-01 18:44 UTC, tzdybal approved these changes
Numbers are matching ECIP.

2020-03-02 09:00 UTC, q9f approved these changes
LGMT

Tested on Mordor on block 945_xxx this morning.

Mordor will fork in 7-14 days if the head stabilizes.

2020-03-02 09:00 UTC, q9f commented
To recover Kotti, I would wait for client releases

2020-03-02 12:51 UTC, merged